trigger:
  branches:
    include:
      - 'master'
  tags:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build_Parser
        displayName: Build
        steps:
          - task: CacheBeta@0
            inputs:
              key: 'gradle | api | $(Agent.OS)'
              path: '$(GRADLE_USER_HOME)'
            displayName: Configure build cach

          - script: |
              mkdir -p $(GRADLE_USER_HOME)
              cat << EOF > $(GRADLE_USER_HOME)/gradle.properties
              mavenUser=$(mvn.username)
              mavenPassword=$(mvn.password)
              EOF
            displayName: Configure artifact repository credentials

          - task: Gradle@2
            inputs:
              workingDirectory: ''
              gradleWrapperFile: 'gradlew'
              gradleOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              tasks: 'build'
              options: '--build-cache'
            displayName: Compile & Build

          - task: Gradle@2
            displayName: Release
            condition: startsWith(variables['Build.SourceBranch'], 'refs/tags')
            inputs:
              gradleWrapperFile: 'gradlew'
              gradleOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              tasks: 'publish'